### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by Recialhot** [jyf588/transformer-inertial-poser#16]
when i run  offline_testing_simple.py ,it causes:

Traceback (most recent call last):
  File "transformer-inertial-poser/offline_testing_simple.py", line 460, in <module>
    print(np.max(losses_angle), test_files_included[np.argmax(losses_angle)])
  File "<__array_function__ internals>", line 180, in amax
  File ".conda/envs/avatarjlm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File ".conda/envs/avatarjlm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

thanks your help

**Comment by amaliacontiero** [comment]
The error states that it can't apply the np.max function because 'losses_angle' is possibly an empty array. 

Possibly a data problem. My advice is to make sure that you have all the necessary data in the source folder beforehand.
And follow steps (1-2-3) of the README as 2nd step preprocesses the DIP and TotalCapture data to be used in "offline-testing". You can use pre-trained model "output/model-without-dip9and10.pt" in evaluation.
