### ISSUE TITLE
The problem about viz_generated_sbp.py

### ISSUE THREAD

**Issue by huzijun1996** [jyf588/transformer-inertial-poser#18]
Traceback (most recent call last):
  File "viz_generated_sbp.py", line 22, in <module>
    import sim_agent
ModuleNotFoundError: No module named 'sim_agent'

Traceback (most recent call last):
  File "viz_generated_sbp.py", line 31, in <module>
    from transformers.utils import set_seed
ImportError: cannot import name 'set_seed' from 'transformers.utils' (/home/xxx/anaconda3/envs/tip22/lib/python3.8/site-packages/transformers/utils/__init__.py)

I cannot find sim_agent. I cannot find set_seed from transformers.util. What should I do?

**Comment by amaliacontiero** [comment]
As mentioned by the author, viz_generated_sbp.py is an uncleaned script and you need to modify it to get it to work.

For starters, these two errors can be fixed by replacing line 22 with "import bullet_agent" and line 31 with "from learning_utils import set_seed". Look at the rest of the python files for useful tools and the commented out code and args of viz_generated_sbp.py to get your desired result. You need to edit accordingly.

**Comment by huzijun1996** [comment]
Thank you for your answer. My problem has been resolved.
